### ISSUE TITLE
DSR Meeting

### ISSUE THREAD

**Issue by pchainho** [AlticeLabsProjects/matter-poc#18]
```[tasklist]
### Tasks
- [ ] DAC + Yocto: runtime: confirmed?
- [ ] What are the tasks and responsibilities between teams?
- [ ] CHIPTool compilation to Yocto recipe. Reference https://github.com/nxp-imx/meta-matter/tree/f820902be4ccee5115473a4017b1894c222fbd59 -> AP for DSR?
- [ ] Python for DAC: Ok
- [ ] SDK AWS compilation to Yocto recipe. Reference https://github.com/aws4embeddedlinux/meta-aws 
```

**Comment by pchainho** [comment]
- confirmado o uso de DAC + Yocto
- modelo trabalho: Altice Home disponibiliza imagem e GEN10 team instala e corre os testes de "aceitação"
- é preciso confirmar o Yocto 4.0 (é suportado pelo RDK)
